# Generated by Django 4.2.1 on 2023-05-31 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='qrCode',
            field=models.ImageField(blank=True, upload_to='items/'),
        ),
    ]
