# Generated by Django 4.2.1 on 2023-06-05 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_metadatascheme_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='metadataName',
            field=models.CharField(blank=True, max_length=250, unique=True),
        ),
        migrations.AddField(
            model_name='metadata',
            name='metadataUnit',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='metadataType',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='metadatascheme',
            name='metadataSchemeCreator',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='metadatascheme',
            name='metadataSchemeName',
            field=models.CharField(blank=True, max_length=250, unique=True),
        ),
    ]
