# Generated by Django 4.2.1 on 2023-06-06 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_item_metadatascheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='metadata',
            field=models.ManyToManyField(through='api.ItemMetadata', to='api.metadata'),
        ),
        migrations.AlterField(
            model_name='itemmetadata',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_metadata', to='api.item'),
        ),
    ]
