# Generated by Django 4.2.1 on 2023-06-06 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_item_metadata_alter_itemmetadata_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='metadata',
        ),
        migrations.DeleteModel(
            name='ItemMetadata',
        ),
    ]
