# Generated by Django 4.2.1 on 2023-06-09 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_researchsample_samplemetadata_samplescheme_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metadata',
            name='samples',
        ),
        migrations.RemoveField(
            model_name='researchsample',
            name='schemes',
        ),
        migrations.AddField(
            model_name='researchsample',
            name='scheme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.metadatascheme'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='scheme',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='metadata_attributes', to='api.metadatascheme'),
        ),
    ]
