# Generated by Django 4.2.1 on 2023-06-09 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_researchsample_scheme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='scheme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metadata_attributes', to='api.metadatascheme'),
        ),
    ]
