# Generated by Django 4.2.1 on 2023-06-09 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_metadata_scheme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchsample',
            name='scheme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.metadatascheme'),
        ),
    ]
