# Generated by Django 4.2.1 on 2023-06-09 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_researchsample_scheme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchsample',
            name='qrCode',
            field=models.ImageField(blank=True, null=True, upload_to='items/'),
        ),
    ]
