# Generated by Django 4.2.1 on 2023-06-13 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_researchsample_qrcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='name',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
