# Generated by Django 4.2.1 on 2023-06-13 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_metadata_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='samplemetadata',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='samplemetadata',
            name='metadata',
        ),
        migrations.AddField(
            model_name='samplemetadata',
            name='name',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='samplemetadata',
            name='type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='samplemetadata',
            name='unit',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
